services:
  node:
    restart: "unless-stopped"
    stop_grace_period: 3m
    image: chainfliplabs/chainflip-node:${NODE_TAG}
    volumes:
      - node-data:/etc/chainflip
      - ./keys:/etc/chainflip/keys
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${NODE_P2P_PORT:-30333}:${NODE_P2P_PORT:-30333}/tcp
    healthcheck:
      test: ["CMD-SHELL", "true"] # I don't have curl so just wait 30s
      start_period: 30s
      interval: 10s
      timeout: 5s
    entrypoint:
      - /usr/local/bin/chainflip-node
      - --chain
      - /etc/chainflip/perseverance.chainspec.json
      - --base-path
      - /etc/chainflip/chaindata
      - --node-key-file
      - /etc/chainflip/keys/node_key_file
      - --validator
      - --prometheus-external
      - --port
      - ${NODE_P2P_PORT:-30333}
      - --unsafe-rpc-external
      - --rpc-cors=*
      - --rpc-methods
      - unsafe
      - --log
      - ${LOG_LEVEL}
      - --database
      - ${DB_TYPE}
      - --sync
      - ${SYNC_MODE}
    command: ${NODE_EXTRAS}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9615
      - metrics.network=chainflip

  engine:
    restart: "unless-stopped"
    image: chainfliplabs/chainflip-engine:${ENGINE_TAG}
    ulimits:
      nofile:
        soft: 16000
        hard: 16000
    environment:
      - RUST_LOG=${LOG_LEVEL}
    volumes:
      - engine-data:/etc/chainflip
      - ./keys:/etc/chainflip/keys
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${ENGINE_P2P_PORT:-8078}:${ENGINE_P2P_PORT:-8078}/tcp
    depends_on:
      node:
        condition: service_healthy
    entrypoint:
      - /usr/local/bin/chainflip-engine
      - --btc.rpc.http_endpoint
      - ${BTC_RPC}
      - --btc.rpc.basic_auth_user
      - ${BTC_USER}
      - --btc.rpc.basic_auth_password
      - ${BTC_PASSWORD}
      - --btc.backup_rpc.http_endpoint
      - ${BTC_BACKUP_RPC}
      - --btc.backup_rpc.basic_auth_user
      - ${BTC_BACKUP_USER}
      - --btc.backup_rpc.basic_auth_password
      - ${BTC_BACKUP_PASSWORD}
      - --dot.rpc.http_endpoint
      - ${DOT_RPC}
      - --dot.rpc.ws_endpoint
      - ${DOT_WS}
      - --dot.backup_rpc.http_endpoint
      - ${DOT_BACKUP_RPC}
      - --dot.backup_rpc.ws_endpoint
      - ${DOT_BACKUP_WS}
      - --eth.rpc.http_endpoint
      - ${ETH_RPC}
      - --eth.rpc.ws_endpoint
      - ${ETH_WS}
      - --eth.backup_rpc.http_endpoint
      - ${ETH_BACKUP_RPC}
      - --eth.backup_rpc.ws_endpoint
      - ${ETH_BACKUP_WS}
      - --eth.private_key_file
      - /etc/chainflip/keys/ethereum_key_file
      - --arb.rpc.http_endpoint
      - ${ARB_RPC}
      - --arb.rpc.ws_endpoint
      - ${ARB_WS}
      - --arb.backup_rpc.http_endpoint
      - ${ARB_BACKUP_RPC}
      - --arb.backup_rpc.ws_endpoint
      - ${ARB_BACKUP_WS}
      - --arb.private_key_file
      - /etc/chainflip/keys/ethereum_key_file
      - --hub.rpc.http_endpoint
      - ${HUB_RPC}
      - --hub.rpc.ws_endpoint
      - ${HUB_WS}
      - --hub.backup_rpc.http_endpoint
      - ${HUB_BACKUP_RPC}
      - --hub.backup_rpc.ws_endpoint
      - ${HUB_BACKUP_WS}
      - --sol.rpc.http_endpoint
      - ${SOL_RPC}
      - --sol.backup_rpc.http_endpoint
      - ${SOL_BACKUP_RPC}
      - --health_check.hostname
      - 0.0.0.0
      - --health_check.port
      - "5555"
      - --p2p.ip_address
      - ${HOST_IP}
      - --p2p.port
      - ${ENGINE_P2P_PORT:-8078}
      - --p2p.node_key_file
      - /etc/chainflip/keys/node_key_file
      - --signing.db_file
      - /etc/chainflip/data.db
      - --state_chain.signing_key_file
      - /etc/chainflip/keys/signing_key_file
      - --state_chain.ws_endpoint
      - ws://node:9944
      - --prometheus.hostname
      - 0.0.0.0
      - --prometheus.port
      - "5566"
    command: ${ENGINE_EXTRAS}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=5566
      - metrics.network=chainflip

  cli:
    restart: "no"
    profiles: ["tools"]
    image: chainfliplabs/chainflip-cli:${CLI_TAG}
    volumes:
      - ./keys:/etc/chainflip/keys
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - /usr/local/bin/chainflip-cli
      - --state_chain.signing_key_file
      - /etc/chainflip/keys/signing_key_file
      - --state_chain.ws_endpoint
      - ws://node:9944

volumes:
  node-data:
  engine-data:
